### ISSUE TITLE
Horizontal container splitter drag not working on page load

### ISSUE THREAD

**Issue by JimVanEeden** [leefsmp/Re-Flex#27] opened 2017-10-04 08:19 UTC
I've found that when refreshing the page, my splitter can't be dragged in a horizontal container (vertical doesn't have this problem). When routing away and then to the page, it works again.

Also, the splitter seems to be a bit thinner for some reason when it doesn't work.

I can't give much more information than this sadly, there are no errors or warnings whatsoever. (I've tested this with the examples as well, same results).

Edit:
Some other thing I've noticed is that the ReflexElements do not get an inline style on them in the HTML when it's broken.

**Comment by leefsmp** [comment] 2017-10-04 08:24
Can you provide more info, such as what do you mean exactly by "when refreshing the page" ... is it hitting reload button on the browser? Which browser are you using? On which platform, mobile or desktop? 

Thanks

**Comment by JimVanEeden** [comment] 2017-10-04 08:27
Yes I mean hitting the reload button. This is on a desktop, both chrome and firefox have the same problem.

**Comment by leefsmp** [comment] 2017-10-04 08:34
Can you provide a recording of the problem? I can't reproduce that on my side, what is your browser version? By definition reloading the page will reload all the code, so I don't see how it could produce different result ...

**Comment by JimVanEeden** [comment] 2017-10-04 08:57
[react-reflex-bug.zip](https://github.com/leefsmp/Re-Flex/files/1355150/react-reflex-bug.zip)

Hope this helps. I've tried to remove as much stuff from the app as possible. Also, instead of routing through a link I've just hot-reloaded the app to get it working again (webpack). Note that the vertical splitter works perfectly fine in all cases.

**Comment by leefsmp** [comment] 2017-10-04 09:05
You are running on Ubuntu, maybe it's specific to that platform. I'm not able to reproduce that behavior on OSX or Windows. You could try to run reflex from the source in your app and add traces in ReflexSplitter to see what's going on. Could be a problem with how events are fired on ubuntu. I haven't tested this platform myself :s

**Comment by JimVanEeden** [comment] 2017-10-04 09:14
Alright I'll have a look at it at some later point. For now I'll just work with the non-resizable panels. Thanks.

**Comment by JimVanEeden** [comment] 2017-10-10 09:57
I've just created a pull request which fixes the problem for me: https://github.com/leefsmp/Re-Flex/pull/28

The reason it didn't work is that on ComponentDidMount where computePixelFlex (eventually) gets called, domElement.offsetHeight returns 0. Not exactly sure why. It seems the component is not fully rendered yet or something, so calling it again on componentDidUpdate fixes it. Kind of a dirty fix, so if you can find a more elegant way to solve it, even better.

**Comment by leefsmp** [comment] 2017-10-10 12:36
I'm a bit reluctant to place a call to `setState` in `componentDidUpdate`... Could you give a try at the modified `computePixelFlex` method below and see if it fixes the behavior in a nicer way:
```computePixelFlex () {

    const domElement = ReactDOM.findDOMNode(this)

    switch (this.props.orientation) {

      case 'horizontal':

        return 1.0 / domElement.offsetHeight

      case 'vertical':

        return 1.0 / domElement.offsetWidth

      default :

        return 0
    }
  }```

**Comment by leefsmp** [comment] 2017-10-10 12:39
I'm a bit reluctant to place a call to `setState` in `componentDidUpdate`. I will see if I can setup an ubuntu VM and work on a nicer fix.

**Comment by JimVanEeden** [comment] 2017-11-28 12:20
Any updates on this?

**Comment by leefsmp** [comment] 2017-11-29 01:19
I didn't have time to set up a dev env for that, I will probably not have time before Jan/feb next year :(

**Comment by loopmode** [comment] 2018-03-27 14:35
Had a similar bug, using create-react-app in development mode. Was always reproducible with horizontal, but didn't happen with vertical.

Turns out, my "global" `import "./styles/styles.scss";` in `src/index.js` was happening _after_ components got initialized.
My global stylesheet was supposed to set some content heights, e.g. via `flex: 1` or `height: 100%`, but had not done this yet. As a consequence, the height of the container element was 0 here:
https://github.com/leefsmp/Re-Flex/blob/361a92bb943af12727ebfffee4d19c0840691eb9/src/lib/ReflexContainer.jsx#L523

in turn, pixelFlex was `1 / 0 = Infinity` and things went south.

For now, I simply delay the very first render in `src/index.js` via timeout - that way, my global stylesheet is loaded and applied, elements/containers have height when reflex measures, and everything seems good for now.

**Comment by leefsmp** [comment] 2018-03-27 15:35
You should make sure the container of the `ReflexContainer` has it's `height` set by css otherwise this will cause trouble as you described above. Some browsers my have issues if the `height` is set to `100%` but none of the parent has a defined height, to fix that I am setting the `height` of the body to `100vh` for example. 

If you can provide a reproducible sample that is not tied to a specific platform/browser I am happy to take a look.

**Comment by loopmode** [comment] 2018-03-27 15:51
Note that in my case, the issue was tied to the actual environment. 
The production build worked just fine, because of less webpack/HMR magic and styles properly extracted to a stylesheet.

In my opinion, there's not much to be fixed, but you could give a more helpful error message when height is 0. 
While I had a feeling for what's happening right when I saw the mention of `Infinity`, many users will not have that intuition.

**Comment by leefsmp** [comment] 2018-03-29 14:51
I've added a warning in v.2.2.1. I'll close the issue for now unless there is a concrete reproducible case.

```
computePixelFlex () {

    const domElement = ReactDOM.findDOMNode(this)

    switch (this.props.orientation) {

      case 'horizontal':

        if (domElement.offsetHeight === 0.0) {
          console.warning(
            'Found ReflexContainer with height=0, ' +
            'this will cause invalid behavior...')
          console.warning(domElement)
          return 0.0
        }

        return 1.0 / domElement.offsetHeight

      case 'vertical':
      default:

        if (domElement.offsetWidth === 0.0) {
          console.warning(
            'Found ReflexContainer with width=0, ' +
            'this will cause invalid behavior...')
          console.warning(domElement)
          return 0.0
        }

        return 1.0 / domElement.offsetWidth
    }
  }
```

**Closed by leefsmp** 2018-03-29 14:51 UTC

**Comment by barbalex** [comment] 2018-11-14 13:05
I am hitting this warning. Sometimes. But not all times. Seems to depend on some sort of timing issue.

This happens on Windows in dev mode.

**Comment by leefsmp** [comment] 2018-11-15 15:00
Can't really try to reproduce based on such thin description. Does the layout behave as expected? ... in which case I assume you could ignore that warning. Could it be due to hot reloading updates?

**Comment by barbalex** [comment] 2018-11-15 15:08
> Can't really try to reproduce based on such thin description

Yeah, I couldn't either :-(

> Does the layout behave as expected?

Height is 0, so nothing is shown. Even though data has arrived in the meantime and so divs should have been built and height should be > 0. And with the exception of the sporadic times when the error does not occur and everything renders perfectly

> Could it be due to hot reloading updates?

While checking on the live site to answer your question I just realized that things work out just as bad there: Sometimes everything works nicely. Most times this warning is logged and nothing rendered: `Found ReflexContainer with width=0, this will cause invalid behavior...`

So It seems to have nothing to do with hot reloading.

**Comment by barbalex** [comment] 2018-11-15 15:10
This is the component's code: https://github.com/barbalex/apf2/blob/master/src/components/Ekf/index.js

**Comment by leefsmp** [comment] 2018-11-15 15:42
I'm not sure to understand exactly your decription, it is not easy to figure out quickly the behavior from the component your referenced in the link. I haven't used lazy loading at the component level in any of my apps but it seems to me the content a 'ReflexElement` should not impact at all the behavior of the parent `ReflexContainer`. I will check that on a simpler example. 

If you can set up a more basic online example feel free to update that thread.

**Comment by barbalex** [comment] 2018-11-15 16:36
Do you have a Project on CodeSandbox or any similar service that I could fork and try to provoke this behaviour with?

I am not experienced with those tools.

Before asking this I checked if a link to such a project is provide when I open a new issue. Some Github projects offer this and it usually compels me to try building a demo of the behaviour.

**Comment by leefsmp** [comment] 2018-11-15 21:57
I have several codepen demos like this [one](https://codepen.io/leefsmp/pen/eQByqd) to test stuff about reflex. I am not sure if it would be possible to set up a lazy loaded component on such platform ...

**Comment by barbalex** [comment] 2019-04-06 15:51
This is biting me again pretty hard:

- rather frequently in dev mode
- every now and then in production
- 100% of the time when testing using cypress (which I have only just begun) :-(

Will need to invetigate further. Or use another tool which would be sad because apart from this react-reflex has been great.

**Comment by barbalex** [comment] 2019-04-06 15:59
The weird thing is: Although I set the flex prop to 0.33 on the first ReflexElement, the console shows that flex is set to `flex: 0 1 0%;`
<img width="511" alt="2019-04-06_17h55_44" src="https://user-images.githubusercontent.com/669783/55671956-ac8ffe00-5895-11e9-8160-43c34f2db8f9.png">

**Comment by aysenurela** [comment] 2019-12-17 12:45
Hello there, I think I observe a similar problem, I am using v2.0.11 react-reflex and v0.1.64 react-split-pane. react-reflex rendered inside react-split-pane

![react-reflex under react-split](https://user-images.githubusercontent.com/40861089/70996509-f3e8b280-20e3-11ea-975a-168a7edf322c.PNG)

when I try to use flex splitter reflex-elements take increadible small flex values screenshots attached. Are there any solutions for this?

![smal values](https://user-images.githubusercontent.com/40861089/70996538-0cf16380-20e4-11ea-800a-3b219106ced0.PNG)

**Comment by leefsmp** [comment] 2019-12-17 13:14
Can't really tell much based on the screenshots, do you have a pen/sandbox demo which can repro the issue? Alternatively a proper code sample that can help test the issue? Also any reason why you cannot use a more recent version of `react-reflex`?

**Comment by akphi** [comment] 2020-10-29 18:45
> The weird thing is: Although I set the flex prop to 0.33 on the first ReflexElement, the console shows that flex is set to `flex: 0 1 0%;`
> <img alt="2019-04-06_17h55_44" width="511" src="https://user-images.githubusercontent.com/669783/55671956-ac8ffe00-5895-11e9-8160-43c34f2db8f9.png">

@leefsmp  Don't think I can reproduce this error in production, but if it happens during development, for me, it is exactly like what happened to @loopmode 

> Had a similar bug, using create-react-app in development mode. Was always reproducible with horizontal, but didn't happen with vertical.
> 
> Turns out, my "global" `import "./styles/styles.scss";` in `src/index.js` was happening _after_ components got initialized. Although it's the first line of the first file - must be something with webpack, `style-loader`/`sass-loader` wooes.
> 
> The stylesheet was supposed to set some content heights via `flex: 1` or `height: 100%`, but had not done this yet

I think one of the way to create this is using `webpack` with `style-loader` and then choke the browser a bit by hitting refresh continuously and then wait, then I will get what described by @barbalex 

So for me, the most concrete workaround is to make sure calling the below at the entry of the app: basically programmatically set those style to the HTML document (must be at the very beginning to avoid overriding user-defined styles)

```javascript
if (process.env.NODE_ENV === 'development') {
    const stylesheet = document.createElement('style');
    stylesheet.innerHTML = `
      /* For development, this needs to be injected before stylesheet, else \`react-reflex\` panel dimension calculation will be off */
      .reflex-container { height: 100%; width: 100%; }
      .reflex-container.horizontal { flex-direction: column; min-height: 1px; }
      .reflex-container.vertical { flex-direction: row; min-width: 1px; }
      .reflex-container > .reflex-element { height: 100%; width: 100%; }
      .reflex-container > .reflex-element > .reflex-size-aware { height: 100%; width: 100%; }`;
    document.head.prepend(stylesheet);
}
```

@leefsmp Can't thank you enough. I was rather disappointed at the performance, API, and lack of care in the `react-split-pane` project, but feel stuck with it for its popularity, but then I couldn't quite stand it when I see what this library can do, really hope that this could be a good option for me: so far this is the only issue that I have bumped into. And really hope this will work well with React 17+, so fingers crossed 🤞

**Comment by nickgros** [comment] 2021-02-23 19:15
I was running into this issue and I managed to hack together a quick workaround that solved my problems by using [`react-sizeme`](https://www.npmjs.com/package/react-sizeme):

```jsx
<SizeMe>
  {({ size }) => (
	<ReflexContainer key={(!!size).toString()} {...otherProps} >
		{/* your ReflexElements here */}
	</ReflexContainer>
  )}
</SizeMe>
```

I set the key to the boolean value of the `size` because I don't actually want the `ReflexContainer` to re-render when the size changes.

Not totally sure how it's fixing the issue, but I would guess by delaying the `ReflexContainer` render until a valid size has been set, because I no longer get the console warnings.

**Comment by lmossman** [comment] 2023-06-16 00:22
@leefsmp I am also running into this problem; I have opened a new issue for it and included a reproducible example here: https://github.com/leefsmp/Re-Flex/issues/186
