### ISSUE TITLE
ReflexContainer computeFlexDataRec infinite loop

### ISSUE THREAD

**Issue by JimVanEeden** [leefsmp/Re-Flex#38] opened 2017-11-28 14:43 UTC
On Ubuntu 16.04, Firefox 57.0, the computeFlexDataRec function in the ReflexContainer goes into an infinite loop. There is no problem on Chrome on the same computer, and there is also no problem on the same Firefox version on a Mac.

**Comment by leefsmp** [comment] 2018-01-17 07:08
I can't reproduce the issue on my side, I tested with a virtual Ubuntu 16.04 against Firefox 57.0 [...](https://www.screencast.com/t/OXGivCCTQ1V)
https://www.screencast.com/t/OXGivCCTQ1V

**Comment by leefsmp** [comment] 2018-01-17 15:07
I'm closing that for the time being. Feel free to submit more details on how to repro that issue. Thanks

**Closed by leefsmp** 2018-01-17 15:07 UTC
